ResumeSiteWithMvc/Controllers/adminGirisController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using ResumeSiteWithMvc.Models.entity;

namespace ResumeSiteWithMvc.Controllers
{
    [AllowAnonymous]
    public class adminGirisController : Controller
    {

        // GET: adminGiris
        resumeEntities1 db = new resumeEntities1();
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult girisYap(tblAdminGiris p)
        {

            var adminBilgileri = db.tblAdminGiris.FirstOrDefault(x => x.adminKullaniciAdi == p.adminKullaniciAdi && x.adminSifre == p.adminSifre);
            if (adminBilgileri != null)
            {
                FormsAuthentication.SetAuthCookie(adminBilgileri.adminKullaniciAdi, false);
                Session["adminKullaniciAdi"] = adminBilgileri.adminKullaniciAdi.ToString();
                return RedirectToAction("Index", "adminPanelAnasayfa");
            }
            else
            {
                ModelState.AddModelError("","Lütfen kullanıcı adı ve şifrenizi kontrol edin.");
                return View("Index", p);

            }
        }
    }
}

ResumeSiteWithMvc/Views/adminGiris/Index.cshtml
@model ResumeSiteWithMvc.Models.entity.tblAdminGiris
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">

<head>
    <title>Material Login Form a Responsive Widget Template :: w3layouts</title>
    <!-- meta tags -->
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="keywords" content="Art Sign Up Form Responsive Widget, Audio and Video players, Login Form Web Template, Flat Pricing Tables, Flat Drop-Downs, Sign-Up Web Templates,
		Flat Web Templates, Login Sign-up Responsive Web Template, Smartphone Compatible Web Template, Free Web Designs for Nokia, Samsung, LG, Sony Ericsson, Motorola Web Design" />
    <!-- /meta tags -->
    <!-- custom style sheet -->
    @*<link href="~/girisYapTemaKodlari/css/style.css" rel="stylesheet" type="text/css" />*@
    <link href="~/girisCss/girisYapCss.css" rel="stylesheet">

    <!-- /custom style sheet -->
    <!-- fontawesome css -->

    <link href="~/girisCss/fontAwesome.css" rel="stylesheet" />
    <!-- /fontawesome css -->
    <!-- google fonts-->
    <link href="//fonts.googleapis.com/css?family=Raleway:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">
    <!-- /google fonts-->

</head>


<body>
    <h1>Hoşgeldiniz</h1>
    <div class=" w3l-login-form">
        <h2>Giriş Yap</h2>

        @using (Html.BeginForm("girisYap", "adminGiris", FormMethod.Post))
        {

            <div class=" w3l-form-group">
                <label>Kullanıcı Adı:</label>
                <div class="group">
                    <input type="text" class="form-control" placeholder="Kullanıcı Adı" name="adminKullaniciAdi" required />
                </div>
            </div>
            <div class=" w3l-form-group">
                <label>Şifre:</label>
                <div class="group">
                    <input type="password" class="form-control" placeholder="Şifre" name="adminSifre" required />
                </div>
                <p style="color:white;">Kullanıcı Adı: admin - Şifre: admin</p>
            </div>
            @*<span style="color:red;">@ViewBag.hataliGiris</span>*@
            @Html.ValidationSummary(true, "", new { @class = "text-danger", @style = "color:red;" })
            <div class="forgot">
                <a href="#">Şifreni Mi Unuttun ?</a>
                <p><input type="checkbox">Beni Hatırla</p>
            </div>
            <button type="submit">Giriş Yap</button>
        }
        <p class=" w3l-register-p">Hala Bir Hesabın Yok mu?<a href="#" class="register"> Kayıt Ol</a></p>
    </div>

</body>

</html>