ResumeSiteWithMvc/Controllers/egitimController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ResumeSiteWithMvc.repositories;
using ResumeSiteWithMvc.Models.entity;
namespace ResumeSiteWithMvc.Controllers
{
    public class egitimController : Controller
    {
        genericRepository<tblEğitimleri> repository = new genericRepository<tblEğitimleri>();
        // GET: egitim
        public ActionResult Index()
        {
            var egitimlerim = repository.list();
            return View(egitimlerim);
        }
        [HttpGet]
        public ActionResult egitimEkle()
        {
            return View();
        }
        public ActionResult egitimEkle(tblEğitimleri p)
        {
            repository.add(p);
            return RedirectToAction("Index");
        }
        public ActionResult egitimSil(int id)
        {
            tblEğitimleri egitim = repository.find(i => i.ıd == id);
            repository.delete(egitim);
            return RedirectToAction("Index");
        }
        public ActionResult egitimGuncellemeSayfasi(int id)
        {
            tblEğitimleri egitim = repository.find(i => i.ıd == id);
            return View(egitim);
        }
        [HttpPost]
        public ActionResult egitimGuncellemeSayfasi(tblEğitimleri p)
        {
            tblEğitimleri egitim = repository.find(i => i.ıd == p.ıd);
            egitim.baslik = p.baslik;
            egitim.altBaslik = p.altBaslik;
            egitim.altBaslik1 = p.altBaslik1;
            egitim.notOrtalamasi = p.notOrtalamasi;
            egitim.tarih = p.tarih;
            repository.update(egitim);
            return RedirectToAction("Index");
        }
    }
}

ResumeSiteWithMvc/Views/egitim/Index.cshtml
@using ResumeSiteWithMvc.Models.entity
@model List<tblEğitimleri>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_adminLayout.cshtml";
}

<h2>Index</h2>

<table class=" table table-bordered">
    <tr>
        <th>Id</th>
        <th>Başlık</th>
        <th>Alt Başlık</th>
        <th>Alt Baslık 2</th>
        <th>Not Ortalaması</th>
        <th>Tarih</th>
        <th>Sil</th>
        <th>Güncelle</th>
    </tr>
    <tbody>
        @foreach(var i in Model)
            {
                <tr>
                    <td>@i.ıd</td>
                    <td>@i.baslik</td>
                    <td>@i.altBaslik</td>
                    <td>@i.altBaslik1</td>
                    <td>@i.notOrtalamasi</td>
                    <td>@i.tarih</td>
                    <td><a href="/egitim/egitimSil/@i.ıd" class="btn btn-warning" >Sil</a></td>
                    <td><a href="/egitim/egitimGuncellemeSayfasi/@i.ıd" class="btn btn-success">Güncelle</a></td>
                </tr>
            }
    </tbody>
</table>

<a href="/egitim/egitimEkle" class="btn btn-primary">Eğitim Ekle</a>

ResumeSiteWithMvc/Views/egitim/egitimEkle.cshtml
@model ResumeSiteWithMvc.Models.entity.tblEğitimleri
@{
    ViewBag.Title = "egitimEkle";
    Layout = "~/Views/Shared/_adminLayout.cshtml";
}

<h2>egitimEkle</h2>

@using (Html.BeginForm("egitimEkle", "egitim", FormMethod.Post))
{
    <div>
        <label>Başlık</label>
        @Html.TextBoxFor(i => i.baslik, new { @class = "form-control" })
        @Html.ValidationMessageFor(i => i.baslik, "", new { @style = "color:red;" })
    </div>
    <div>
        <label>Alt Başlık</label>
        @Html.TextBoxFor(i => i.altBaslik, new { @class = "form-control" })
        @Html.ValidationMessageFor(i => i.altBaslik, "", new { @style = "color:red;" })
    </div>
    <div>
        <label>Alt Başlık 1</label>
        @Html.TextBoxFor(i => i.altBaslik1, new { @class = "form-control" })
        @Html.ValidationMessageFor(i => i.altBaslik1, "", new { @style = "color:red;" })
    </div>
    <div>
        <label>Not Ortalması</label>
        @Html.TextBoxFor(i => i.notOrtalamasi, new { @class = "form-control" })
        @Html.ValidationMessageFor(i => i.notOrtalamasi, "", new { @style = "color:red;" })
    </div>
    <div>
        <label>Tarih</label>
        @Html.TextBoxFor(i => i.tarih, new { @class = "form-control" })
    </div>
    <button class="btn btn-primary">Eğitim Ekle</button>
    @Html.HiddenFor(i => i.ıd)
}

ResumeSiteWithMvc/Views/egitim/egitimGuncellemeSayfasi.cshtml
@model ResumeSiteWithMvc.Models.entity.tblEğitimleri
@{
    ViewBag.Title = "egitimGuncellemeSayfasi";
    Layout = "~/Views/Shared/_adminLayout.cshtml";
}

<h2>egitimGuncellemeSayfasi</h2>

@using (Html.BeginForm("egitimGuncellemeSayfasi", "egitim", FormMethod.Post))
{
    <div>
        <label>Başlık</label>
        @Html.TextBoxFor(i => i.baslik, new { @class = "form-control" })
        @Html.ValidationMessageFor(i => i.baslik, "", new { @style = "color:red;" })
    </div>
    <div>
        <label>Alt Başlık</label>
        @Html.TextBoxFor(i => i.altBaslik, new { @class = "form-control" })
    </div>
    <div>
        <label>Alt Başlık 1</label>
        @Html.TextBoxFor(i => i.altBaslik1, new { @class = "form-control" })
    </div>
    <div>
        <label>Not Ortalması</label>
        @Html.TextBoxFor(i => i.notOrtalamasi, new { @class = "form-control" })
    </div>
    <div>
        <label>Tarih</label>
        @Html.TextBoxFor(i => i.tarih, new { @class = "form-control" })
    </div>
    <button class="btn btn-primary">Eğitim Güncelle</button>
    @Html.HiddenFor(i => i.ıd)
}