ResumeSiteWithMvc/Controllers/projelerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ResumeSiteWithMvc.Models.entity;
using ResumeSiteWithMvc.repositories;
namespace ResumeSiteWithMvc.Controllers
{
    public class projelerController : Controller
    {
        // GET: projeler
        genericRepository<tblProjeler> repository = new genericRepository<tblProjeler>();
        public ActionResult Index()
        {
            var projeler = repository.list();
            return View(projeler);
        }
        [HttpGet]
        public ActionResult projeEkle()
        {
            return View();
        }
        [HttpPost]
        public ActionResult projeEkle(tblProjeler p)
        {
            repository.add(p);
            return RedirectToAction("Index");
        }

        public ActionResult projeSil(int id)
        {
            tblProjeler proje = repository.find(i => i.id == id);
            repository.delete(proje);
            return RedirectToAction("Index");
        }

        public ActionResult projeGuncellemeSayfasi(int id)
        {
            tblProjeler proje = repository.find(i => i.id == id);
            return View(proje);
        }
        [HttpPost]
        public ActionResult projeGuncellemeSayfasi(tblProjeler p)
        {
            tblProjeler proje = repository.find(i => i.id == p.id);
            proje.Proje = p.Proje;
            repository.update(proje);
            return RedirectToAction("Index");
        }
    }
}

ResumeSiteWithMvc/Views/projeler/Index.cshtml
@using ResumeSiteWithMvc.Models.entity
@model List<tblProjeler>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_adminLayout.cshtml";
}

<h2>Projeler</h2>

<table class="table table-bordered">
    <tr>
        <th>Id</th>
        <th>Proje</th>
        <th>Sil</th>
        <th>Güncelle</th>
    </tr>

    <tbody>
        @foreach (var i in Model)
        {
            <tr>
                <td>@i.id</td>
                <td>@i.Proje</td>
                <td><a href="/projeler/projeSil/@i.id" class="btn btn-warning">Sil</a></td>
                <td><a href="/projeler/projeGuncellemeSayfasi/@i.id" class="btn btn-success">Güncelle</a></td>
            </tr>
        }
    </tbody>
</table>

<a href="/projeler/projeEkle" class="btn btn-primary">Proje Ekle</a>

ResumeSiteWithMvc/Views/projeler/projeEkle.cshtml
@model ResumeSiteWithMvc.Models.entity.tblProjeler
@{
    ViewBag.Title = "projeEkle";
    Layout = "~/Views/Shared/_adminLayout.cshtml";
}

<h2>projeEkle</h2>

@using (Html.BeginForm("projeEkle", "projeler", FormMethod.Post))
{
    <div class="form-group">
        <label>Proje Giriniz</label>
        @Html.TextBoxFor(i => i.Proje, new { @class = "form-control" })
        @Html.ValidationMessageFor(i => i.Proje, "", new { @style = "color:red;" })
    </div>
    <button class="btn btn-primary">Proje Ekle</button>
    @Html.HiddenFor(i => i.id)

}

ResumeSiteWithMvc/Views/projeler/projeGuncellemeSayfasi.cshtml
@model ResumeSiteWithMvc.Models.entity.tblProjeler
@{
    ViewBag.Title = "projeGuncellemeSayfasi";
    Layout = "~/Views/Shared/_adminLayout.cshtml";
}

<h2>projeGuncellemeSayfasi</h2>


@using (Html.BeginForm("projeGuncellemeSayfasi", "projeler", FormMethod.Post))
{
    <div class="form-group">
        <label>Proje Giriniz</label>
        @Html.TextBoxFor(i => i.Proje, new { @class = "form-control" })
    </div>
    <button class="btn btn-primary">Proje Güncelle</button>
    @Html.HiddenFor(i => i.id)

}