ResumeSiteWithMvc/Controllers/hobiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ResumeSiteWithMvc.repositories;
using ResumeSiteWithMvc.Models.entity;
namespace ResumeSiteWithMvc.Controllers
{
    public class hobiController : Controller
    {
        // GET: hobi
        genericRepository<tblHobilerim> repository = new genericRepository<tblHobilerim>();
        public ActionResult Index()
        {
            var hobilerim = repository.list();
            return View(hobilerim);
        }
        [HttpGet]
        public ActionResult hobiEkle()
        {
            return View();
        }
        [HttpPost]
        public ActionResult hobiEkle(tblHobilerim p)
        {

            repository.add(p);
            return RedirectToAction("Index");
        }
        public ActionResult hobiSil(int id)
        {
            tblHobilerim hobi = repository.find(i => i.ıd == id);
            repository.delete(hobi);
            return RedirectToAction("Index");
        }
        public ActionResult hobiGuncellemeSayfasi(int id)
        {
            tblHobilerim hobi = repository.find(i => i.ıd == id);
            return View(hobi);
        }
        [HttpPost]
        public ActionResult hobiGuncellemeSayfasi(tblHobilerim p)
        {
            tblHobilerim hobi = repository.find(i => i.ıd == p.ıd);
            hobi.hobi = p.hobi;
            repository.update(hobi);
            return RedirectToAction("Index");
        }
    }
}

ResumeSiteWithMvc/Views/hobi/Index.cshtml
@using ResumeSiteWithMvc.Models.entity
@model List<tblHobilerim>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_adminLayout.cshtml";
}

<h2>Hobilerim</h2>

<table class="table table-bordered">
    <tr>
        <th>Id</th>
        <th>Hobi</th>
        <th>Sil</th>
        <th>Güncelle</th>
    </tr>

    <tbody>
        @foreach(var i in Model)
            {
                <tr>
                    <td>@i.ıd</td>
                    <td>@i.hobi</td>
                    <td><a href="/hobi/hobiSil/@i.ıd" class="btn btn-warning">Sil</a></td>
                    <td><a href="/hobi/hobiGuncellemeSayfasi/@i.ıd" class="btn btn-success">Güncelle</a></td>
                </tr>
            }
    </tbody>
</table>

<a href="/hobi/hobiEkle" class="btn btn-primary">Hobi Ekle</a>

ResumeSiteWithMvc/Views/hobi/hobiEkle.cshtml
@model ResumeSiteWithMvc.Models.entity.tblHobilerim
@{
    ViewBag.Title = "hobiEkle";
    Layout = "~/Views/Shared/_adminLayout.cshtml";
}

<h2>hobiEkle</h2>

@using (Html.BeginForm("hobiEkle", "hobi", FormMethod.Post))
{
    <div class="form-group">
        <label>Hobi Giriniz</label>
        @Html.TextBoxFor(i => i.hobi, new { @class = "form-control" })
        @Html.ValidationMessageFor(i => i.hobi,"", new { @style = "color:red;" })
    </div>
    <button class="btn btn-primary">Hobi Ekle</button>
    @Html.HiddenFor(i => i.ıd)

}

ResumeSiteWithMvc/Views/hobi/hobiGuncellemeSayfasi.cshtml
@model ResumeSiteWithMvc.Models.entity.tblHobilerim
@{
    ViewBag.Title = "hobiGuncellemeSayfasi";
    Layout = "~/Views/Shared/_adminLayout.cshtml";
}

<h2>hobiGuncellemeSayfasi</h2>

@using (Html.BeginForm("hobiGuncellemeSayfasi", "hobi", FormMethod.Post))
{
    <div class="form-group">
        <label>Hobi Giriniz</label>
        @Html.TextBoxFor(i => i.hobi, new { @class = "form-control" })
    </div>
    <button class="btn btn-primary">Hobi Güncelle</button>
    @Html.HiddenFor(i => i.ıd)

}